### PR TITLE
Created model.py and addred requirements and gitignore.

### PR DESCRIPTION
**Pull request by ekmerline**
New model.py file, the requirements.txt file, and gitignore.

### CODE REVIEW

**Review by mmrice22 — COMMENTED** [review]
I'll accept said change

**Review by christinababaya — COMMENTED** [review]
Yes, I approve of the new features added in.

**Review by mmrice22 — APPROVED** [review]
I approve these changes once more

**Review by christinababaya — APPROVED** [review]
I approve of the added features.

**Pull request merged**
